fix exception when type schema json contains x-psx-mapping attr
apioo/psx-schema pull request #28
Opened 2024-12-11 11:35 UTC by AMar4enko

I ran into an edge using psx/schema to generate PHP DTOs from TypeScript via intermediary TypeSchema json representation.  
On TypeScript side, I have field metadata, identifying source DB field name, that is in underscore case. I was looking for an option to capture this field name mapping into TypeSchema. After a quick look into the repo, I discovered I could make use of custom `x-psx-mapping` TypeSchema JSON attribute (which isn't documented btw).  

This commit fixes PHP parser/generator combo exception when dealing with x-psx-mapping attribute.

2024-12-19 17:53 UTC, chriskapp requested changes

2024-12-19 17:53 UTC, chriskapp commented on src/Parser/TypeSchema/BCLayer.php
> +
Hey @AMar4enko thanks for the PR, in general `x-psx-mapping` is only a `psx/schema` specific implementation detail which is not available at the [TypeSchema](https://typeschema.org/) spec. But we can of course also parse this, could you explain a little bit why this is needed, the specific attributes are parsed at s. `psx-schema/src/Parser/TypeSchema.php:164` so it should already work?

2024-12-19 17:53 UTC, chriskapp commented on tests/Generator/resource/source_typeschema.json
> +        "format": "format"
This has the wrong format, it should be a map with string values but in general we could also remove this

2024-12-19 19:00 UTC, AMar4enko commented
Hey @chriskapp thank you for the feedback!  
Alright, I was in doubts which file this particular fix belongs, decided to put it in BCLayer.php since I felt it served as kind of data normalization layer prior parsing step. As you correctly pointed out, TypeSchema parser does consider custom `x-psx` properties and stores them into type attributes. Please have a look at https://github.com/apioo/psx-schema/blob/40d639e8afc2d992af177df5a88378bc9a9261ec/src/Generator/CodeGeneratorAbstract.php#L136  
It expects `mapping` type attribute (which gets parsed from `x-psx-mapping` attribute of TypeSchema definition JSON) in form of associative array, whereas parser by default parses JSON into stdClass tree. Thus adding `x-psx-mapping` attribute to TypeSchema JSON causes all code generators throw an error when mapping attribute value of stdClass gets treated as associative array. As to small addition to source_typeschema.json - it triggers the edgecase in such a way it doesn't break any other tests.

2024-12-20 10:20 UTC, chriskapp commented
@AMar4enko  ok, I have also looked into this in detail and this indeed a bug at the TypeSchema parser, good catch, I think the fix is fine but could you adjust the test cases a little bit, we should move this to the TypeSchema parser test case and there we can compare the attributes which we already have, I have created a patch which shows the adjustments s.
[fix_parse_mapping_attribute.patch](https://github.com/user-attachments/files/18209275/fix_parse_mapping_attribute.patch)

2025-01-29 20:31 UTC, chriskapp commented
I have just tagged a version and applied the patch so it is now fixed in the latest version.

2025-01-29 20:31 UTC, closed without merging